sudo: required

language: c

services:
    - docker

before_install:
    - cp travis/* .

install:
    - ./mk_dockerfile.sh
    - docker-compose build

script:
    - docker-compose run $(bash <(curl -s https://codecov.io/env)) tests

notifications:
    email:
        on_success: change
        on_failure: always

env:
    - PG_VERSION=14
    - PG_VERSION=14 LEVEL=hardcore
    - PG_VERSION=13
    - PG_VERSION=13 LEVEL=hardcore
    - PG_VERSION=12
    - PG_VERSION=12 LEVEL=hardcore
    - PG_VERSION=11
    - PG_VERSION=11 LEVEL=hardcore
    - PG_VERSION=10
    - PG_VERSION=10 LEVEL=hardcore

